APPLICATION = mintest 

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT

QUIET ?= 1

USEMODULE += random

include $(RIOTBASE)/Makefile.include
