APPLICATION = msg_snd_rcv

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT

QUIET ?= 1

include $(RIOTBASE)/Makefile.include
